import type { Metadata } from "next";
import "@styles/globals.css";
import { Nanum_Gothic } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//font setting
const nanumGothic = Nanum_Gothic({
  subsets: ["latin"],
  weight: ["400", "700", "800"], // 사용할 굵기 지정
  display: "swap", // 폰트 표시 방식 설정
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={nanumGothic.className}>
      <body>{children}</body>
    </html>
  );
}
